on:
  push:
    branches:
      - main

name: Build

jobs:
  example:
    name: Build example.nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: example.nix
        run: nix-build example.nix

  example-19_07:
    name: Build example-19.07.nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: example-19.07.nix
        # NIXPKGS_ALLOW_INSECURE for python2
        run: NIXPKGS_ALLOW_INSECURE=1 nix-build example-19.07.nix

  example-x86-64:
    name: Build example-x86-64.nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: example-x86-64.nix
        # NIXPKGS_ALLOW_INSECURE for python2
        run: nix-build example-x86-64.nix
